kontent-ai/smart-link

README.md

Improve README:
- add code examples
- better description
- section about configuration
- badges

KCL-4842 Finish README and examples

---

.prettierrc.js

Fix end of line setting in Prettier.

Fix end of line in prettier

---

.editorconfig
README.md
example/index.html
package-lock.json
src/index.ts
src/lib/HighlightRenderer.ts
src/lib/IFrameCommunicator.ts
src/lib/NodeSmartLinkProvider.ts
src/plugin.ts
src/scss/styles.scss
src/utils/node.ts
src/utils/validation.ts

- Fix line ending config.
- Add support for CSS animations (animationend, transitionend).
- Move `cursor: pointer` to CSS.
- Rename `NodeVisibilityThreshold` to `MinimumVisiblePartForHighlight`.
- Rename all iframe message types (`kontent` -> `kontent-smart-link`).
- Change rendering logic. Highlights are now rendered to the closest relatively positioned parent node.
- Display hovered highlight on top of the non-hovered one.

KCL-4985 JS SDK improvements

---

.eslintrc.js
.gitignore
README.md
karma.conf.js
package-lock.json
package.json
test-browser/plugin.spec.ts
test-browser/test-helpers/createHtmlFixture.ts
test-browser/test-helpers/createTestEventManager.ts
test-browser/test-helpers/generateRandomString.ts
test-browser/utils/dataAttributes.spec.ts
test-browser/utils/link.spec.ts
test-browser/utils/node.spec.ts
test-browser/utils/query.spec.ts
test-browser/utils/storage.spec.ts

- Setup karma and jasmine
- Prepare test helpers
- Prepare basic unit tests for utils

KCL-4843 Prepare unit tests for SDK

---

CHANGELOG.md
src/lib/EventManager.ts
src/lib/IFrameCommunicator.ts
src/lib/NodeSmartLinkProvider.ts
src/plugin.ts
src/utils/assert.ts
src/utils/dataAttributes.ts
test-browser/utils/dataAttributes.spec.ts

- Add metadata to click event (targetRect).

KCL-5356 Add metadata to click event

---

CHANGELOG.md
src/scss/styles.scss
webpack.common.config.js

- Change default SDK styles.
- Fix webpack rules for SCSS.

KCL-6433 Reskin smart link sdk

---

src/lib/IFrameCommunicator.ts
src/lib/IFrameCommunicatorTypes.ts
src/lib/NodeSmartLinkProvider.ts
src/plugin.ts
src/utils/createUuid.ts
src/utils/link.ts
src/utils/validation.ts

KCL-6794 - SDK initial message with response core + dummy handler

---

package-lock.json
package.json

v2.0.0-alpha.0

---

src/lib/IFrameCommunicator.ts
src/lib/IFrameCommunicatorTypes.ts
src/lib/NodeSmartLinkProvider.ts
src/utils/validation.ts

KCL-6793 - Edit btn components

---

package-lock.json
package.json

Release 2.0.0 alpha.1

---

src/lib/IFrameCommunicatorTypes.ts
src/utils/validation.ts
src/web-components/KSLAddButtonElement.ts

KCL-6902 Disable plus button if not allowed to use

---

src/web-components/KSLAddButtonElement.ts
src/web-components/KSLButtonElement.ts

- Both popover buttons are disabled when parent item is published.
- Fix styles for disabled button.

KCL-6903 Add button - published item scenario

---

package-lock.json
package.json

2.0.0-alpha.2

---

src/lib/IFrameCommunicatorTypes.ts
src/web-components/KSLAddButtonElement.ts

KCL-7089 Fix multiple permissions cases

---

package-lock.json
package.json

2.0.0-alpha.3

---

.github/workflows/pull-request.yml
BREAKING.md
CHANGELOG.md
README.md
package-lock.json
package.json

- Update README & CHANGELOG
- Create BREAKING
- `npm audit fix`

KCL-6894 Update README, CHANGELOG & BREAKING

---

CHANGELOG.md
src/lib/NodeSmartLinkProvider.ts
src/web-components/KSLAddButtonElement.ts

- Fixed the problem with infinite loading when data attributes required for add button were missing.

KCL-7226 Missing data attributes keep add button in progress state

---

CHANGELOG.md
src/sdk.ts

- Fix highlight blinking when iframe communication is initialized

KCL-7248 Fix highlights blinking when iframe communication is initialized

---

src/lib/IFrameCommunicator.ts
src/lib/IFrameCommunicatorTypes.ts
src/sdk.ts
src/utils/reload.ts

KCL-7449 - Added refresh message handler

---

CHANGELOG.md
README.md
src/lib/IFrameCommunicator.ts
src/lib/NodeSmartLinkProvider.ts
src/sdk.ts

- Closes #68 
- Add a new message to README
- Add an environment check before using browser APIs

KCL-7407 Make it more clear that SDK works only in browser

---

README.md
TROUBLESHOOTING.md

- Create TROUBLESHOOTING.md
- Add links to README.md
- Closes #19

KCL-8097 Create TROUBLESHOOTING

---

README.md
package-lock.json
package.json

KCL-12587 Live Preview [Public]

---

CHANGELOG.md

KCL-12587 - Release 3.2.0 changelog update

---

package-lock.json
package.json
src/index.ts

export IUpdateMessageElement
